-- cities cities
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities (id INT UNIQUE AUTO_INCREMENT PRIMARY KEY NOT NULL, state_id FOREIGN KEY REFERENCES states(id), name VARCHAR(256));
